### PR TITLE
Fix inf loop when order get status failed. Fixes #47

### LINKED ISSUE #47: Inifnite loop when order get status failed
There seems to be and inifinite loop when you get redirected back from swedbank pay with the status "failed"

To recreate this problem you can use these card deatails "4761739001010416 12/22 268" and when you get to the page you choose "failed" in the dropdown 4 times in a row.

An exampel on a fix that seems to work for me is: 
```
elseif ($status == 'failed'){
  break;
}
```
in public function thankyou_page at line 665 in the file swedbank-pay-payments/includes/class-wc-gateway-swedbank-pay-cc.php

### PR DESCRIPTION
**Pull request by aait**

### CODE REVIEW

File: includes/class-wc-gateway-swedbank-pay-cc.php [hunk 1]
```diff
@@ -657,36 +659,45 @@ public function thankyou_page( $order_id ) {
...
+								$this->adapter->log(
+									LogLevel::WARNING,
+									sprintf( 'Failed transaction: (%s), (%s), (%s), (%s), (%s), (%s), (%s)',
+										$order_id,
+										$payment_id,
+										$transaction->getId(),
+										$transaction->getData('failedReason'),
+										$transaction->getData('failedActivityName'),
+										$transaction->getData('failedErrorCode'),
+										$transaction->getData('failedErrorDescription')
```
Comment (asbjornu) [inline includes/class-wc-gateway-swedbank-pay-cc.php:693]: Don't use the `failedXxx` fields, [use the `problem` field with its RFC 7807 defined fields](https://developer.swedbankpay.com/payments/card/other-features#transaction-problems) instead.

**Review by asbjornu — CHANGES_REQUESTED** [review]

File: includes/class-wc-gateway-swedbank-pay-cc.php (hunk 1 above)
Comment (aait) [reply includes/class-wc-gateway-swedbank-pay-cc.php:693]: @asbjornu We don't show the problem to customer. We need to know the details of the problem and we log this

Comment (asbjornu) [reply includes/class-wc-gateway-swedbank-pay-cc.php:693]: Yes, but these fields are being deprecated. Use the ones found in `problem` instead.

**Review by asbjornu — APPROVED** [review]
